In [1]:
from bbq.decoder import d_osd, bp_osd
import numpy as np

In [15]:
h_eff = np.array([[0, 0, 1, 1], [0, 1, 1, 1], [0, 1, 1, 0]])
prior = np.array([[0.9, 0.1], [0.9, 0.1], [0.8, 0.2], [0.8, 0.2]])

p = 0.1
field = 2
max_iter = 1000

n_dets, n_qudits = h_eff.shape
real_error = np.zeros(n_qudits, dtype=int)
rand = np.random.rand(n_qudits)
for err in range(n_qudits):
    if rand[err] < prior[err, 1]:
        real_error[err] = 1
syndrome = (h_eff @ real_error) % field

print(f'h_eff = \n {h_eff}')
print(f'prior = \n {prior}')
print(f'real_error = \n {real_error}')
print(f'syndrome = \n {syndrome}')

h_eff = 
 [[0 0 1 1]
 [0 1 1 1]
 [0 1 1 0]]
prior = 
 [[0.9 0.1]
 [0.9 0.1]
 [0.8 0.2]
 [0.8 0.2]]
real_error = 
 [0 1 0 1]
syndrome = 
 [1 0 1]


In [16]:
error, success = d_osd(field, h_eff, syndrome, prior, debug=False)

assert success
assert (error == real_error).all()

In [17]:
error, success = bp_osd(field, h_eff, syndrome, prior, max_iter, debug=False)

assert success
assert (error == real_error).all()